name: expense_tracker
description: A professional Expense Tracker built with Flutter, Provider, and Hive.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5+1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Date & Currency Formatting
  intl: ^0.20.2

  # UUID Generator
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/